#
# Configuration for Signals Toolkit
#
# Adjust as needed!
#
BACKUP_DIR=/backup/toolkit
DATA_DIR=/data/toolkit

DB_HOST=localhost
DB_NAME=toolkit_db
DB_USER=toolkit_user

LOCKFILE=$DATA_DIR/logs/toolkit.lock
OPENEJB_XML=$INSTALL_DIR/conf/toolkit_openejb.xml
TRUSTSTORE=$INSTALL_DIR/conf/truststore.jks
VERSION=1.0.5
